MVC_RememberWords/Controllers/GroupsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DAL_RememberWords.Context;
using DAL_RememberWords.Entities;
using Microsoft.AspNet.Identity;

namespace MVC_RememberWords.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        // GET: Groups
        public ActionResult Index()
        {
            ViewBag.word = (from w in  db.Words.ToList()
                            where w.Date <= DateTime.Now.Date && w.Group.UserId == User.Identity.GetUserId()
                            select w).ToList().Count;
            var result = from g in db.Groups.ToList()
                        where g.UserId==User.Identity.GetUserId()
                        select g;
            return View(result.ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Group group)
        {
            if (ModelState.IsValid)
            {
                group.UserId = User.Identity.GetUserId();
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpGet]
        public ActionResult Start()
        {
            var words = from w in db.Words.ToList()
                            where w.Date <= DateTime.Now.Date && w.Group.UserId == User.Identity.GetUserId()
                            select w;
            if (words.ToList().Count == 0)
            {
                return RedirectToAction("Index");
            }
            Word word = words.ToList()[new Random().Next(words.ToList().Count)];
            return View(word);
        }
        [HttpPost]
        public ActionResult Start(int Id, string result)
        {
            if (ModelState.IsValid)
            {
                Word oldWord = db.Words.Find(Id);
                if (oldWord.Discription.Split(' ').Contains(result))
                {
                    oldWord.Date = DateTime.Now.AddDays(oldWord.Level).Date;
                    oldWord.Level *= 2;
                    ViewBag.result = true;
                    ViewBag.components = oldWord.Discription.Split(' ');
                }
                else
                {
                    oldWord.Level = oldWord.Level == 1 ? oldWord.Level : oldWord.Level/2;
                    ViewBag.result = false;
                    ViewBag.components = oldWord.Discription.Split(' ');
                }
                db.Entry(oldWord).State = EntityState.Modified;
                db.SaveChanges();
            }
            return View("Result");
        }
    
    }
}

MVC_RememberWords/Controllers/WordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL_RememberWords.Context;
using DAL_RememberWords.Entities;
using Microsoft.AspNet.Identity;

namespace MVC_RememberWords.Controllers
{
    [Authorize]
    public class WordsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Words
        public ActionResult Index(int? groupId)
        {
            ViewBag.groupId = groupId;
            ViewBag.GroupName = (from g in db.Groups
                where g.Id == groupId
                select g.Name).SingleOrDefault();
            var result = from w in db.Words.ToList()
                         where w.GroupId == groupId
                         select w;
            return View(result.ToList());
        }

        // GET: Words/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Word word = db.Words.Find(id);
            if (word == null)
            {
                return HttpNotFound();
            }
            return View(word);
        }

        // GET: Words/Create
        public ActionResult Create(int? groupId)
        {
            ViewBag.groupId = groupId;
            return View();
        }

        // POST: Words/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,WordValue,Discription")] Word word, int? groupId)
        {
            if (ModelState.IsValid)
            {
                word.Level = 1;
                word.Date = DateTime.Now.Date;
                word.GroupId = (int)groupId;
                db.Words.Add(word);
                db.SaveChanges();
                return RedirectToAction("Index",new { groupId = groupId});
            }

            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Name", word.GroupId);
            return View(word);
        }

        // GET: Words/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Word word = db.Words.Find(id);
            if (word == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Name", word.GroupId);
            return View(word);
        }

        // POST: Words/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,WordValue,Discription,Level,Date")] Word word)
        {
            if (ModelState.IsValid)
            {
                Word oldWord = db.Words.Find(word.Id);
                oldWord.WordValue = word.WordValue;
                oldWord.Discription = word.Discription;
                oldWord.Date = word.Date;
                oldWord.Level = word.Level;
                db.Entry(oldWord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index",new {groupId = oldWord.GroupId});
            }
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "Name", word.GroupId);
            return View(word);
        }

        // GET: Words/Delete/5
        public ActionResult Delete(int? id,int? groupId)
        {
            ViewBag.groupId = groupId;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Word word = db.Words.Find(id);
            if (word == null)
            {
                return HttpNotFound();
            }
            return View(word);
        }

        // POST: Words/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int? groupId)
        {
            Word word = db.Words.Find(id);
            db.Words.Remove(word);
            db.SaveChanges();
            return RedirectToAction("Index", new { groupId = groupId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_RememberWords/Views/Groups/Create.cshtml
@model DAL_RememberWords.Entities.Group

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="hidden" name="groupId" value="@ViewBag.groupId" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_RememberWords/Views/Groups/Delete.cshtml
@model DAL_RememberWords.Entities.Group

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC_RememberWords/Views/Groups/Details.cshtml
@model DAL_RememberWords.Entities.Group

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Посмотреть Слова", "Index", "Words",new { groupId = Model.Id},null) |
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_RememberWords/Views/Groups/Edit.cshtml
@model DAL_RememberWords.Entities.Group

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_RememberWords/Views/Groups/Index.cshtml
@model IEnumerable<DAL_RememberWords.Entities.Group>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@Html.ActionLink("Начать обучение ","Start") <h3>@ViewBag.word</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Посмотреть Слова", "Index", "Words", new { groupId = item.Id },null) |
            @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
            @Html.ActionLink("Details", "Details", new {id = item.Id}) |
            @Html.ActionLink("Delete", "Delete", new {id = item.Id})
        </td>
    </tr>
}

</table>

MVC_RememberWords/Views/Groups/Result.cshtml
@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

>@{
     if (ViewBag.result)
     {
         <h2 style="color: Green">Правильно</h2>
        foreach (var component in ViewBag.components)
        {
            <p>@component</p><br />
        }
    }
    else
    {
         <h2 style="color: Red">Не правильно</h2> 
         <h3>Правильно так:</h3>
         foreach (var component in ViewBag.components)
         {
             <p>@component</p><br/>
         }
     }
    @Html.ActionLink("Далее","Start")
}

MVC_RememberWords/Views/Groups/Start.cshtml
@model DAL_RememberWords.Entities.Word

<div>
    <h4>Word</h4>
    <hr />
    <dl class="dl-horizontal">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Word</h4>
                <input type="hidden" name="Id" value="@Model.Id"/>
                <div> @Html.DisplayFor(model => model.WordValue)</div>
                <div class="form-group">
                    @Html.DisplayFor(model => model.WordValue)
                    <div class="col-md-10">
                        <input type="text" name="result"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        }
     </dl>
</div>